# Header
menu:
  Home: /
  WorkFlow: /WorkFlow
  IT-profile: /IT-profile
  Vertaling: /Vertaling
  

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id: